global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using Laraue.EfCoreTriggers.PostgreSql.Extensions;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure;
global using OMNE.Data;
